# Site settings
title: "小船"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chchl.github.io" # the base hostname & protocol for your site
github_username: chchl

timezone: Beijing
gems: ['jekyll-paginate']

# Build settings
highlighter: rouge
permalink: /:categories/:title/

markdown: kramdown
# markdown: redcarpet
redcarpet:
  extensions: ['fenced_code_blocks', 'tables']

paginate: 25
